= Guided solution (page 1)

== Objectives
* Investigate the instance connectivity issue in Red Hat OpenStack Platform.
* Solve the instance connectivity in the hands-on lab environment.

== Outcomes
* Investigate why ssh to instance is not working.
* Fix the ssh to instance failing issue.

== Instructions

1. Break the environment if you have not done it and step through the fix.
+
----
[student@workstation ~]$ ssh stack@director

[stack@director ~]$ source overcloudrc

(overcloud) [stack@director ~]$ lab start bfx022
Running start action against scenario bfx022
Run the following command:
ssh -i /home/stack/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@172.25.250.186
----

2. Run the ssh command from the previous lab command output and notice the Connection timed out error. Also run the ping command against instance IP.
+
----
(overcloud) [stack@director ~]$ ssh -i /home/stack/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@172.25.250.186
ssh: connect to host 172.25.250.186 port 22: Connection timed out

(overcloud) [stack@director ~]$ ping 172.25.250.186 -c 1
PING 172.25.250.186 (172.25.250.186) 56(84) bytes of data.

--- 172.25.250.186 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
----
+
You observe that both ping and ssh attempts failed which indicates lack of connectivity.


3. Access the overcloud environment and determine the specific compute node where the instance is currently running.
+
----
(overcloud) [stack@director ~]$ openstack server list --long
+--------------------------------------+---------------+--------+------------+-------------+----------------------------------------------------+---------------------+--------------------------------------+-------------+--------------------------------------+-------------------+-------------------------------------+------------+
| ID                                   | Name          | Status | Task State | Power State | Networks                                           | Image Name          | Image ID                             | Flavor Name | Flavor ID                            | Availability Zone | Host                                | Properties |
+--------------------------------------+---------------+--------+------------+-------------+----------------------------------------------------+---------------------+--------------------------------------+-------------+--------------------------------------+-------------------+-------------------------------------+------------+
| 4756da74-4ba2-4172-ae37-0333d3f8c164 | scenario-5-vm | ACTIVE | None       | Running     | scenario-5-network=172.25.250.186, 192.168.150.162 | cirros-0.5.2-x86_64 | 06e98912-2ccc-439a-b19b-5a67c2bff6f3 | m1.tiny     | 3ab59dd5-f848-4bb7-becb-c4b4ac459507 | nova              | overcloud-novacompute-1.localdomain |            |
+--------------------------------------+---------------+--------+------------+-------------+----------------------------------------------------+---------------------+--------------------------------------+-------------+--------------------------------------+-------------------+-------------------------------------+------------+
----
+
You observe that it is overcloud-novacompute-1.
+
[NOTE]
====
The RHOSP cluster is configured to operate with Distributed Virtual Routing (DVR) functionality.
====

4. Examine the ARP cache on the director VM.
+
----
(overcloud) [stack@director ~]$ ip neighbor | grep 172.25.250.186
172.25.250.186 dev eth0 lladdr fa:16:3e:1d:72:81 STALE
----
+
- An entry with the floating IP associated with a MAC address, indicating successful ARP negotiation.

- This signifies functional communication via ARP, but ICMP communication remains problematic.

- Proceed to verify whether the packets are being correctly routed to the appropriate node.

5. Now check whether the packets are being correctly routed to the appropriate node. Run the below command to access the compute node on which the instance is hosted.
+
----
(overcloud) [stack@director ~]$ ssh tripleo-admin@overcloud-novacompute-1.localdomain

[tripleo-admin@overcloud-novacompute-1 ~]$ sudo su -

[root@overcloud-novacompute-1 ~]# ovs-vsctl show
. . .
    Bridge br-ex
        fail_mode: standalone
        Port ens4
            Interface ens4
        Port br-ex
            Interface br-ex
                type: internal
. . .
----
+
Take a note that the inteface name ens4 is associated with the external bridge br-ex in the output.


6. To verify incoming traffic, initiate a tcpdump on this interface and try to ping the instance from another terminal.
+
----
[root@overcloud-novacompute-1 ~]# tcpdump -envvi ens4 icmp
dropped privs to tcpdump
tcpdump: listening on ens4, link-type EN10MB (Ethernet), snapshot length 262144 bytes
08:50:27.128216 52:54:00:04:fa:0b > fa:16:3e:1d:72:81, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 36758, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.186: ICMP echo request, id 3, seq 1, length 64
08:50:40.189080 52:54:00:04:fa:0b > fa:16:3e:1d:72:81, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 37708, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.186: ICMP echo request, id 4, seq 1, length 64
08:51:00.718370 52:54:00:04:fa:0b > fa:16:3e:1d:72:81, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 46124, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.186: ICMP echo request, id 5, seq 1, length 64
. . .
----
+
- You observe that ICMP echo requests arriving at the machine.

- The presence of ICMP echo requests reaching the external NIC on the compute node indicates the proper functioning of the Distributed Virtual Router (DVR).

- However, you observed that echo requests are not receiving the echo replies on the director VM.

7. Determine the tap interface used for the instance on the compute node.
+
----
(overcloud) [stack@director ~]$ openstack port list --server scenario-bfx022-vm
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                             | Status |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| 888f43d5-70fe-4373-bb3f-271dc003d4bd |      | fa:16:3e:3f:58:7c | ip_address='192.168.150.162', subnet_id='04f47564-3a42-4eed-bdc8-a4a7bd9c0d54' | ACTIVE |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
----

8. This interface is named in the format tap followed by the initial part of the port ID. For instance, here the port ID is 888f43d5-70fe-4373-bb3f-271dc003d4bd and the associated tap interface would be tap888f43d5-70.
+
----
[root@overcloud-novacompute-1 ~]# ip l show tap888f43d5-70
18: tap888f43d5-70: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1442 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:3f:58:7c brd ff:ff:ff:ff:ff:ff
----

9. Execute a tcpdump on this tap interface on attempting to ping the instance.
+
----
[root@overcloud-novacompute-1 ~]# tcpdump -envvi tap888f43d5-70
dropped privs to tcpdump
tcpdump: listening on tap888f43d5-70, link-type EN10MB (Ethernet), snapshot length 262144 bytes
10:20:45.702021 fa:16:3e:e4:57:e8 > fa:16:3e:3f:58:7c, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 49554, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 192.168.150.162: ICMP echo request, id 8, seq 1, length 64
10:21:01.903078 fa:16:3e:e4:57:e8 > fa:16:3e:3f:58:7c, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 50376, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 192.168.150.162: ICMP echo request, id 9, seq 1, length 64
10:23:02.551100 fa:16:3e:e4:57:e8 > fa:16:3e:3f:58:7c, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 37890, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 192.168.150.162: ICMP echo request, id 10, seq 1, length 64
. . .
----
+
- Successful delivery of the echo request to the tap interface linked with the instance indicates that the network path and connectivity mechanisms are operating correctly.

- All indicators appeared satisfactory from the Neutron perspective.* The underlying networking infrastructure, including OVN components, is functioning as intended.

- It appeared that the virtual machine (VM) failed to generate a reply when the echo request reached it.

- The problem might reside within the VM's internal configuration or its behavior towards incoming requests.

- Access the instance's console for further investigation on this issue.

