= Guided solution (page 1)

== Objectives
* Investigate the instance connectivity issue in Red Hat OpenStack Platform.
* Solve the instance connectivity in the hands-on lab environment.

== Outcomes
* Investigate why ssh to instance is not working.
* Fix the ssh to instance failing issue.

== Instructions

1. Break the environment if you have not done it and step through the fix.
+
----
[student@workstation ~]$ lab start bfx022
Running start action against scenario bfx022
Run the following command:
ssh -i /home/student/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@192.168.51.159
----

2. Run the ssh command from the previous lab command output and notice the Connection timed out error. Also run the ping command against instance IP.
+
----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@192.168.51.159
ssh: connect to host 192.168.51.159 port 22: Connection timed out

[student@workstation ~]$ ping 192.168.51.159 -c 1
PING 192.168.51.159 (192.168.51.159) 56(84) bytes of data.

--- 192.168.51.159 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
----
+
You observe that both ping and ssh attempts failed which indicates lack of connectivity.


3. Access the overcloud environment and determine the specific compute node where the instance is currently running.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server list --long
+--------------------------------------+--------------------+--------+------------+-------------+---------------------------------------------------------+---------------------+--------------------------------------+---------+-------------------+---------------------------+------------+-------------+
| ID                                   | Name               | Status | Task State | Power State | Networks                                                | Image Name          | Image ID                             | Flavor  | Availability Zone | Host                      | Properties | Host Status |
+--------------------------------------+--------------------+--------+------------+-------------+---------------------------------------------------------+---------------------+--------------------------------------+---------+-------------------+---------------------------+------------+-------------+
| 3ad8f3fe-0757-47d8-8f98-816500a50076 | scenario-bfx022-vm | ACTIVE | None       | Running     | scenario-bfx022-network=192.168.150.128, 192.168.51.159 | cirros-0.5.2-x86_64 | 10210206-c30a-4765-8547-0dad335b5675 | m1.tiny | nova              | compute02.srv.example.com |            | UP          |
+--------------------------------------+--------------------+--------+------------+-------------+---------------------------------------------------------+---------------------+--------------------------------------+---------+-------------------+---------------------------+------------+-------------+
----
+
You observe that it is compute02.srv.example.com.
+
[NOTE]
====
The RHOSP cluster is configured to operate with Distributed Virtual Routing (DVR) functionality.
====

4. Examine the ARP cache on the utility server.
+
----
[student@workstation ~]$ ssh lab@utility
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Fri Apr  4 09:09:47 2025 from 172.25.250.9
[lab@utility ~]$ ip neighbor | grep 192.168.51.159
192.168.51.159 dev eth2 lladdr fa:16:3e:69:ad:e6 STALE
----
+
- An entry with the floating IP associated with a MAC address, indicating successful ARP negotiation.

- This signifies functional communication via ARP, but ICMP communication remains problematic.

- Proceed to verify whether the packets are being correctly routed to the appropriate node.

5. Now check whether the packets are being correctly routed to the appropriate node. Run the below command to access the compute node on which the instance is hosted.
+
----
[student@workstation ~]$ ssh root@compute02.srv.example.com

[root@compute02 ~]# ovs-vsctl show
. . .
    Bridge br-ex
        fail_mode: standalone
        Port br-ex
            Interface br-ex
                type: internal
        Port patch-provnet-84157851-395c-40eb-a3ec-6b512dd58759-to-br-int
            Interface patch-provnet-84157851-395c-40eb-a3ec-6b512dd58759-to-br-int
                type: patch
                options: {peer=patch-br-int-to-provnet-84157851-395c-40eb-a3ec-6b512dd58759}
        Port eth2
            Interface eth2
. . .
----
+
Take a note that the inteface name eth2 is associated with the external bridge br-ex in the output.


6. To verify incoming traffic, initiate a tcpdump on this interface and try to ping the instance from another terminal.
+
----
[root@compute02 ~]# tcpdump -envvi eth2 icmp
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
14:56:44.898428 52:54:00:02:33:fe > fa:16:3e:69:ad:e6, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 39626, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.51.159: ICMP echo request, id 19, seq 1, length 64
14:56:45.920249 52:54:00:02:33:fe > fa:16:3e:69:ad:e6, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 40247, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.51.159: ICMP echo request, id 19, seq 2, length 64
14:56:46.944097 52:54:00:02:33:fe > fa:16:3e:69:ad:e6, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 41189, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.51.159: ICMP echo request, id 19, seq 3, length 64
. . .
----
+
- You observe that ICMP echo requests arriving at the machine.

- The presence of ICMP echo requests reaching the external NIC on the compute node indicates the proper functioning of the Distributed Virtual Router (DVR).

- However, you observed that echo requests are not receiving the echo replies on the director VM.

7. Determine the tap interface used for the instance on the compute node.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack port list --server scenario-bfx022-vm
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                             | Status |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| 524a77d9-8b27-49af-b007-acdb0f3805df |      | fa:16:3e:14:5e:b8 | ip_address='192.168.150.128', subnet_id='645a620b-0143-4465-a709-e514e14354f1' | ACTIVE |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
----

8. This interface is named in the format tap followed by the initial part of the port ID. For instance, here the port ID is 524a77d9-8b27-49af-b007-acdb0f3805df and the associated tap interface would be tap524a77d9-8b.
+
----
[root@compute02 ~]# ip l show tap524a77d9-8b
29: tap524a77d9-8b: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1442 qdisc fq_codel master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:14:5e:b8 brd ff:ff:ff:ff:ff:ff
----

9. Execute a tcpdump on this tap interface on attempting to ping the instance.
+
----
[root@compute02 ~]# tcpdump -envvi tap524a77d9-8b
dropped privs to tcpdump
tcpdump: listening on tap524a77d9-8b, link-type EN10MB (Ethernet), snapshot length 262144 bytes
14:59:13.802448 fa:16:3e:d1:ce:dc > fa:16:3e:14:5e:b8, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 62, id 39053, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.150.128: ICMP echo request, id 20, seq 1, length 64
14:59:14.847952 fa:16:3e:d1:ce:dc > fa:16:3e:14:5e:b8, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 62, id 39328, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.150.128: ICMP echo request, id 20, seq 2, length 64
14:59:15.872120 fa:16:3e:d1:ce:dc > fa:16:3e:14:5e:b8, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 62, id 39733, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.150.128: ICMP echo request, id 20, seq 3, length 64
. . .
----
+
- Successful delivery of the echo request to the tap interface linked with the instance indicates that the network path and connectivity mechanisms are operating correctly.

- All indicators appeared satisfactory from the Neutron perspective.* The underlying networking infrastructure, including OVN components, is functioning as intended.

- It appeared that the virtual machine (VM) failed to generate a reply when the echo request reached it.

- The problem might reside within the VM's internal configuration or its behavior towards incoming requests.

- Access the instance's console for further investigation on this issue.

