= Break-fix Scenario

Objectives:

* Investigate the instance connectivity issue in Red Hat OpenStack Platform.

* Solve the instance connectivity in the hands-on lab environment.

* Familarize with Distributed Virtual Routing (DVR) Functionality.

* Derive the tap interface name.

Scenario:
Your team manages a Red Hat OpenStack Platform (RHOSP) infrastructure used by an important development team for your company. There was a requirement from your internal networking team to have Open Virtual Network (OVN), an open-source software-defined networking (SDN) solution that seamlessly integrates with OpenStack. Recently networking team noticed that there is connectivity issue with instance running in OpenStack envrionment.

They noticed the following error:

----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@192.168.51.159
ssh: connect to host 192.168.51.159 port 22: Connection timed out
----

In the preceding output, ip address can differ in your lab environemnt.

== Recreate scenario

* Recreate this scenario by running the following on workstation as stack user:
----
[student@workstation ~]$ oc login -u admin -p redhatocp https://api.ocp4.example.com:6443
Login successful.

You have access to 76 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "openstack".

[student@workstation ~]$ lab start bfx022
Running start action against scenario bfx022
Run the following command:
ssh -i /home/student/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@192.168.51.159
----

[NOTE]
====
When you run any command with sudo, in case it expects a password then provide the student as a password.
====

- This breaks the connectivity to instance.

- To ensure scenario is recreated, run the ssh command from the previous output:
----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@192.168.51.159
ssh: connect to host 192.168.51.159 port 22: Connection timed out
----
