= Break-fix Scenario

Objectives:

* Investigate the instance connectivity issue in Red Hat OpenStack Platform.

* Solve the instance connectivity in the hands-on lab environment.

* Familarize with Distributed Virtual Routing (DVR) Functionality.

* Derive the tap interface name.

Scenario: 
Your team manages a Red Hat OpenStack Platform (RHOSP) infrastructure used by an important development team for your company. There was a requirement from your internal networking team to have Open Virtual Network (OVN), an open-source software-defined networking (SDN) solution that seamlessly integrates with OpenStack. Recently networking team noticed that there is connectivity issue with instance running in OpenStack envrionment.

They noticed the following error:

----
(overcloud) [stack@director ~]$ ssh -i /home/stack/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@172.25.250.186
ssh: connect to host 172.25.250.186 port 22: Connection timed out
----

In the preceding output, ip address can differ in your lab environemnt.

== Recreate scenario

* Recreate this scenario by running the following on workstation as stack user:
----
[student@workstation ~]$ ssh student@director
Warning: Permanently added 'director' (ED25519) to the list of known hosts.
student@director's password:
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Fri Jan 26 10:45:39 2024 from 172.25.252.254

[student@director ~]$ sudo su - stack
[sudo] password for student:
Last login: Thu Feb 29 10:37:46 EST 2024 from 172.25.250.9 on pts/0

[stack@director ~]$ source overcloudrc

(overcloud) [stack@director ~]$ lab start bfx022
Running start action against scenario bfx022
Run the following command:
ssh -i /home/stack/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@172.25.250.186
----

[NOTE]
====
When you run any command with sudo, in case it expects a password then provide the student as a password.
====

- This breaks the connectivity to instance.

- To ensure scenario is recreated, run the ssh command from the previous output:
----
(overcloud) [stack@director ~]$ ssh -i /home/stack/osp_training/.scenariobfx022/scenario-bfx022-key.pem cirros@172.25.250.186
ssh: connect to host 172.25.250.186 port 22: Connection timed out
----